
package com.test.soapjaxwsspring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustomerServicePortType", targetNamespace = "http://com.test.soap-jax-ws-spring/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerServicePortType {


    /**
     * 
     * @param customerServiceRequest
     * @return
     *     returns com.test.soapjaxwsspring.CustomerServiceResponseType
     */
    @WebMethod(action = "getCustomer")
    @WebResult(name = "CustomerServiceResponse", targetNamespace = "http://com.test.soap-jax-ws-spring/", partName = "CustomerServiceResponse")
    public CustomerServiceResponseType getCustomer(
        @WebParam(name = "CustomerServiceRequest", targetNamespace = "http://com.test.soap-jax-ws-spring/", partName = "CustomerServiceRequest")
        CustomerServiceRequestType customerServiceRequest);

}
